name: Playwright with Hyperexecute
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: Provide LT Username
      accessKey:
        description: Provide LT Access Key
        required: true
        
jobs:
  HyperExecute:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Clone Code
        uses: actions/checkout@v3
      - name: Download CLI and Setting Environment Variables
        shell: bash
        run: |
          curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
          chmod +x hyperexecute
      
      - name: HyperExecute
        shell: bash
        run: |
          ./hyperexecute --user ${{ github.event.inputs.username }} --key ${{ github.event.inputs.accessKey }}  --config .autosplit.yaml
          echo "Your tests are succuessfully completed"
